name: Add new issue to project
on:
  issues:
    types:
      - opened
jobs:
  add_sentry_issue_to_project:
    if: ${{ github.event.issue.user.login == 'sentry-io'}}
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          ORGANIZATION: org-tapadipti
          PROJECT_NUMBER: 1
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectNext(number: $number) {
                  id
                  fields(first:30) {
                    nodes {
                      id
                      name
                      settings
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectNext.id' project_data.json) >> $GITHUB_ENV

      - name: Add issue to project
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh issue edit ${{ github.event.issue.id }} --add-label sentry
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $iss:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $iss}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f iss=$ISSUE_ID --jq '.data.addProjectNextItem.projectNextItem.id')"
